version: '3.8'

services:
  chess-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - MATCHMAKER_RETRY_INTERVAL_MS=${MATCHMAKER_RETRY_INTERVAL_MS}
      - MATCHMAKER_ENQUEUE_TTL_SECONDS=${MATCHMAKER_ENQUEUE_TTL_SECONDS}
      - DEVISE_JWT_SECRET_KEY=${DEVISE_JWT_SECRET_KEY}
    depends_on:
      - db
      - redis
    volumes:
      - .:/chess-api
    command: /bin/sh -c "rm -f tmp/pids/server.pid && rails server -b '0.0.0.0'"

  db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chess_api_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.4.2-alpine
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
